doc_classifier_app/urls.py
from django.urls import path

from . import views



app_name = 'doc_classifier_app'

urlpatterns = [
	# ex: /senti/
    path('', views.index, name='index'),




    path('train/', views.train, name='train'),

	path('test/', views.test, name='test'),

	path('show_wc/', views.create_wordcloud, name='create_wordcloud'),


	path('get_result_sentiment/', views.get_result_sentiment, name='get_result_sentiment'),
]

doc_classifier_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('senti/', include('doc_classifier_app.urls')),
    path('admin/', admin.site.urls),
]

doc_classifier_app/models.py
from django.db import models

# Create your models here.

doc_classifier_app/views.py
from django.shortcuts import render
from django.http import HttpResponse


from django.template import loader




from .scripts import constants
import os

# Create your views here.
def index(request):
	print("hello there")
	print(os.getcwd())
	print(constants.output_results_location)
	print(os.listdir(constants.output_results_location))

	context=constants.update_context()
	template = loader.get_template('doc_classifier_app/index.html')
	return HttpResponse(template.render(context, request))
	# return HttpResponse("Hello, world. You're at the doc_classifier app index.")

from .scripts.train import train_file_model

def train(request):
	print("here in train")
	if request.method == "POST":
		print("In form sub",request.method,request.POST.getlist('models'))
		models_list=request.POST.getlist('models')
		train_file = request.FILES['train_file']
		print("file is ",train_file)
		status=train_file_model(train_file,models_list)
		print("Training status:",status)


		context=constants.update_context()

	template = loader.get_template('doc_classifier_app/index.html')
	return HttpResponse(template.render(context, request))

from .scripts.test import test_model
#to serve files as download
from django.views.static import serve





def test(request):
	print("In form sub")

	if request.method == "POST":
		print("This is post method")
		print("In form sub",request.method,request.POST.getlist('models'))
		models_list=request.POST.getlist('models')
		test_reference_file = request.POST.get("test_reference_file")
		test_text = request.POST.get("text_input")
		print("File to use as reference to test is "+str(test_reference_file)+" and text is "+str(test_text))
		test_file=None

		if 'test_file' in request.FILES:
			test_file = request.FILES['test_file']

		data_result_df,xls_file_path,status=test_model(test_text,test_file,test_reference_file,models_list)
		json_categ=get_categorical_in_json_generic(data_result_df,["SVM","Naive-Bayes"])

		print(json_categ)

		print("The result data is ")
		print(data_result_df.head())


		# saving the data frame as csv
		data_result_df.to_csv(constants.output_results_location+"result.csv")
		print("saved as ",constants.output_results_location,"result.csv")

		sub_key_SVM=list(json_categ["SVM"].keys())
		sub_key_NB=list(json_categ["Naive-Bayes"].keys())

		values_SVM=list(json_categ["SVM"].values())
		values_NB=list(json_categ["Naive-Bayes"].values())

		print(sub_key_SVM,
			sub_key_NB,
			values_NB,
			values_SVM)



		graph_vals = {
		"sub_key_SVM": sub_key_SVM,
		"sub_key_NB": sub_key_NB,
		"values_SVM": values_SVM,
		"values_NB": values_NB
		}


		# configure the csv file to be sent


		g = Graph() 
		context = g.get_context_data(graph_vals) 
		data_result_json=get_json_from_df(data_result_df.head(5))
		context["result"]=data_result_json
		context["columns"]=data_result_df.columns


		print(context.keys())
		return render(request, 'doc_classifier_app/plot_graph.html', context)

def get_json_from_df(df):
	df_dict={}
	cols=df.columns
	print(cols)
	counter=0
	for index,row in df.iterrows():
		this_list=[]
		for col in cols:
			this_list.append(row[col])
		df_dict[counter]=this_list
		counter+=1
	return df_dict

			




from wordcloud import WordCloud
import matplotlib
matplotlib.use('TkAgg')

def create_wordcloud(request):
	print("Going to create_wordcloud")

	test_text = request.POST.get("text_input")

	if test_text is not None:
		wordcloud = WordCloud().generate(test_text)

		# Display the generated image:
		# the matplotlib way:
		import matplotlib.pyplot as plt
		plt.imshow(wordcloud, interpolation='bilinear')
		plt.axis("off")

		plt.savefig(constants.word_cloud_image_location+"img.png")

	

	context={
	"wordcloud":"<img src=/static/img.png>"
	}
	return render(request, 'doc_classifier_app/plot_graph.html', context)

from wsgiref.util import FileWrapper
def get_result_sentiment(request):
	print("Method is ",request.method)
	if request.method=="POST":
		print("At getting")
		filename = constants.output_results_location+"result.csv"
		download_name ="out_senti.csv"
		wrapper = FileWrapper(open(filename))
		response = HttpResponse(wrapper,content_type='text/csv')
		response['Content-Disposition'] = "attachment; filename=%s"%download_name
		return response





from django.views.generic import TemplateView
import plotly.offline as opy
import plotly.graph_objs as go
import plotly.plotly as py

class Graph(TemplateView):
	template_name = 'graph.html'


	def get_context_data(self, graph_vals,**kwargs):
		context = super(Graph, self).get_context_data(**kwargs)

		
		print("values are")

		'''
{'sub_key_SVM': ['business', 'sport', 'entertainment', 'tech', 'politics'], 
'sub_key_NB': ['business', 'sport', 'entertainment', 'tech', 'politics'], 
'values_SVM': [25, 25, 20, 12, 17], 
'values_NB': [26, 25, 20, 11, 17]}


		'''
		# print(graph_vals)

		trace1 = go.Bar(
			x=graph_vals["sub_key_SVM"],
			y=graph_vals["values_SVM"],
			name='SVM'
		)

		trace2 = go.Bar(
			x=graph_vals["sub_key_SVM"],
			y=graph_vals["values_NB"],
			name='Naive-Bayes'
		)

	
		data = [trace1, trace2]



		# layout=go.Layout(title="Meine Daten", xaxis={'title':'x1'}, yaxis={'title':'x2'})

		layout = go.Layout(
			barmode='group'
		)

		figure=go.Figure(data=data,layout=layout)
		div = opy.plot(figure, auto_open=False, output_type='div')

		context['graph'] = div



		#this one was an experimental small graph
		
		# labels = ['Oxygen','Hydrogen','Carbon_Dioxide','Nitrogen']
		# values = [4500,2500,1053,500]
		# trace = go.Pie(labels=labels, values=values)
		# py.iplot([trace], filename='basic_pie_chart')
		# div2 = opy.plot([trace], auto_open=False, output_type='div')
		# print(div2)
		# div2 = opy.plot(fig, auto_open=False, output_type='div')
		# context['graph2'] = div

		return context





def get_categorical_in_json_generic(df,list_of_models):
	dict_categories={}
	print(df.head())
	print(list_of_models)
	for model in list_of_models:
		categories=df[model].unique()
		dict_categories[model]={}
		for category in categories:
			count=df[df[model]==category].shape[0]
			dict_categories[model][category]=count
			print(count)
	return dict_categories
		
		

doc_classifier_app/templates/doc_classifier_app/base.html
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>

<body>
    <div>
        <h2><a href="/">Text Classifier</a></h2>
    </div>
    <div>
        <div>
            <div><h3><a href="/">Train Model</a></h2></div>
            <div>
            {% block train_content %}
            {% endblock %}
            </div>

            

            <div><h3><a href="/">Test Model</a></h2></div>
            <div>
            {% block test_content %}
            {% endblock %}
            </div>



            <div><h3><a href="/">Create Wordcloud</a></h2></div>
            <div>
            {% block create_wordcloud %}
            {% endblock %}
            </div>

            

            <!-- <div><h3><a href="/">Results</a></h2></div>
            <div>
            {% block test_result %}
            {% endblock %}
            </div>
 -->


        </div>
    </div>

</html>

doc_classifier_app/templates/doc_classifier_app/index.html
{% extends 'doc_classifier_app/base.html' %}

{% block train_content %}

<form action="{% url 'doc_classifier_app:train' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if model_list %}
    Select the model/s that you want to train
    <ul>
        {% for model in model_list %}
       <input type="checkbox" name="models" value={{model.name}}>{{model.name}}</br>
        {% endfor %}
    </ul>
    {% else %}
    	<div>No models so far</br></div>
    {% endif %}


    Select the training file:
        <input type="file"  name="train_file" accept=".tsv, .csv" required/>
        </br><button>Submit</button>        

</form>
{% endblock %}







{% block test_content %}
<form action="{% url 'doc_classifier_app:test' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <textarea id="text_input" name="text_input" placeholder="Paste news related to sports, business, entertainment, politics and tech to check the accuracy of trained classifier :)" style="width:300px;height:200px"></textarea></br>

    Select the testing file:
        <input type="file"  name="test_file" accept=".tsv, .csv"/>


    {% if file_list %}
    </br>Select the reference file
    <ul>
        {% for file in file_list %}
    	  <input type="radio" name="test_reference_file" value={{file.name}}>{{file.name}}
          {% for sentiment in file.sentiments %}_{{sentiment}}{% endfor %}


        </br>
        {% endfor %}
    </ul>
    {% else %}
    	<div>No files so far</br></div>
    {% endif %}

    {% if model_list %}
    Select the model/s that you want to use
    <ul>
        {% for model in model_list %}
       <input type="checkbox" name="models" value={{model.name}}>{{model.name}}</br>
        {% endfor %}
    </ul>
    {% else %}
    	<div>No models so far</br></div>
    {% endif %}

    <button>Submit</button>
</form>
{% endblock %}

{% block create_wordcloud %}
<form action="{% url 'doc_classifier_app:create_wordcloud' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <textarea id="text_input" name="text_input" placeholder="Paste Text :)" style="width:300px;height:200px"></textarea></br>

    
    <button>WordCloud</button>
</form>
{% endblock %}


<!-- {% block test_result %}

The result</br>

{{result_list | safe}}

        
{% endblock %} -->

doc_classifier_app/templates/doc_classifier_app/plot_graph.html
<html>

<head>
  <title>Result</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>


{% if result is not None %}
<div>
	<div class="container">
		
    		<table class="table table-striped">
    			<thead>
                  
                  <tr>
                  	{% for col in columns %}
                    <th>{{col}}</th>
                    {%  endfor %}
                  </tr>


                  {% for key, value in result.items  %}
                  <tr>
                  	{% for val in value %}
                  		<td style ="word-break:break-word;">{{val}}</td>
                  	{%  endfor %}

                  </tr>


                  {% endfor %}



                </thead>

    		</table>


	</div>

</div>
{% else %}
<div>
no result coming throgh
</div>
{% endif %}

{% if graph2 %}
<div>
{{ graph2|safe }}
</div>
{% endif %}





{% if graph %}
<div>
{{ graph|safe }}
</div>

<div>
	<form action="{% url 'doc_classifier_app:get_result_sentiment' %}" method="post">
		{% csrf_token %}
		<button>Get Result File</button>
	</form>

</div>
{% endif %}




{% if wordcloud %}
<h1>Wordcloud for Reviews</h1>
<div>
	{{ wordcloud|safe }}
</div>

{% endif %}


</html>